/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package o_osoftwaresuite;
import framescroller.Positioning1;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author SAMUEL
 */
public class O_OAuthenticate extends javax.swing.JFrame {

    /**
     * Creates new form O_OAuthenticate
     */
    public O_OAuthenticate() {
        initComponents();
        initConnection();
        enableScroll();
        authenPanel.setVisible(false);
    }

    
    private void enableScroll(){
    Positioning1 p = new Positioning1(this);
    p.setShouldDoMove(true);
    }
    
      Statement state;
    DriverManager dManager;
    ResultSet rSet;
    Connection connection;
    final String DATABASE = "jdbc:mysql://localhost:3306/o_odb";
    final String USER_NAME = "root";
    final String PASS_WORD = "";

    private void initConnection() {
        try {
            connection = DriverManager.getConnection(DATABASE, USER_NAME, PASS_WORD);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Unable to establish connection" + ex);
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(this, "Unable to establish connection as a result of " + exc);
        } finally {
            JOptionPane.showMessageDialog(this, "Connection Established");
        }
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        selectionCombo = new javax.swing.JComboBox();
        authenPanel = new javax.swing.JPanel();
        userNameTfield = new javax.swing.JTextField();
        passWordTField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pix/gnome_panel_force_quit.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pix/navigate-down-icon.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pix/icons/change password.jpg"))); // NOI18N
        jLabel3.setText("AUTHENTICATION ZONE");

        selectionCombo.setFont(new java.awt.Font("Traditional Arabic", 1, 13)); // NOI18N
        selectionCombo.setForeground(new java.awt.Color(102, 0, 0));
        selectionCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Select Login Type---", "Manager Login", "Staff Login" }));
        selectionCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionComboActionPerformed(evt);
            }
        });

        authenPanel.setBackground(new java.awt.Color(255, 255, 255));
        authenPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aunthentication Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Traditional Arabic", 1, 13), new java.awt.Color(102, 0, 0))); // NOI18N
        authenPanel.setForeground(new java.awt.Color(102, 0, 0));
        authenPanel.setFont(new java.awt.Font("Traditional Arabic", 1, 13)); // NOI18N

        userNameTfield.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter UserName", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Traditional Arabic", 1, 13), new java.awt.Color(102, 0, 0))); // NOI18N

        passWordTField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Traditional Arabic", 1, 13), new java.awt.Color(102, 0, 0))); // NOI18N

        loginButton.setFont(new java.awt.Font("Traditional Arabic", 1, 13)); // NOI18N
        loginButton.setForeground(new java.awt.Color(102, 0, 0));
        loginButton.setText("LOGIN   >   >   >   >");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout authenPanelLayout = new javax.swing.GroupLayout(authenPanel);
        authenPanel.setLayout(authenPanelLayout);
        authenPanelLayout.setHorizontalGroup(
            authenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, authenPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(authenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userNameTfield, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(passWordTField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, authenPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        authenPanelLayout.setVerticalGroup(
            authenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authenPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(userNameTfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(authenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(authenPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(passWordTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, authenPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginButton)
                        .addGap(32, 32, 32))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(authenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(selectionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(authenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectionComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionComboActionPerformed
if(selectionCombo.getSelectedItem().equals("---Select Login Type---")){
authenPanel.setVisible(false);
}
else if(selectionCombo.getSelectedItem().equals("Staff Login")){
authenPanel.setVisible(true);
loginButton.setText("Staff Login >  >");
}
else if(selectionCombo.getSelectedItem().equals("Manager Login")){
authenPanel.setVisible(true);
loginButton.setText("Manager Login  >  >");
}// TODO add your handling code here:
    }//GEN-LAST:event_selectionComboActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
if(selectionCombo.getSelectedItem().equals("Staff Login")){
        if(userNameTfield.getText().equals("") & passWordTField.getText().equals("")){
JOptionPane.showMessageDialog(this, "Missing Parameters, Please fill up", "Error Alert", JOptionPane.ERROR_MESSAGE);
}
else if(userNameTfield.getText().equals("") || passWordTField.getText().equals("")){
JOptionPane.showMessageDialog(this, "Ommited Parameters, Please fill up", "Warning Alert", JOptionPane.WARNING_MESSAGE);
}
else{authenStaff(userNameTfield.getText(), passWordTField.getText());}
}
else if(selectionCombo.getSelectedItem().equals("Manager Login")){
if(userNameTfield.getText().equals("") & passWordTField.getText().equals("")){
JOptionPane.showMessageDialog(this, "Missing Parameters, Please fill up", "Error Alert", JOptionPane.ERROR_MESSAGE);
}
else if(userNameTfield.getText().equals("") || passWordTField.getText().equals("")){
JOptionPane.showMessageDialog(this, "Ommited Parameters, Please fill up", "Warning Alert", JOptionPane.WARNING_MESSAGE);
}
else{authenManager(userNameTfield.getText(), passWordTField.getText());}
}
else{JOptionPane.showMessageDialog(this, "Invalid Login Type, Check Your Selection", "Error Alert", JOptionPane.ERROR_MESSAGE);}// TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
 int x = JOptionPane.showConfirmDialog(this, "Do you really want to close app", "Confirmation Prompt", JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION) {
            System.exit(0);
            
        } else if (x == JOptionPane.NO_OPTION) {
            this.setVisible(true);
        } else {
            this.setVisible(true);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
this.setExtendedState(ICONIFIED);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void authenManager(String userName, String passWord){
        try {
            state =  connection.createStatement();
            final String AUTHEN_STAFF = "Select manager_name from manager_login where user_name = " + "'" + userName + "'" + "and password = " + "'" + passWord + "'";
            rSet =  state.executeQuery(AUTHEN_STAFF);
            if(rSet.next()){
                JOptionPane.showMessageDialog(this, "Login Succesful");
                this.setVisible(false);
                O_OStaffZone.main(new String[]{});
                
                O_OServer.getO_OStaffZone().welcomeLabel.setText("Welcome " + rSet.getObject("manager_name")); }
            else{
                JOptionPane.showMessageDialog(this, "Access Denied..Invalid User..Contact Manager", "Error Alert", JOptionPane.ERROR_MESSAGE);}
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error as a result of " + ex.getMessage(), " Error Exception " , JOptionPane.ERROR_MESSAGE);
        }
    
    }
    
     private void authenStaff(String userName, String passWord){
        try {
            state =  connection.createStatement();
            final String AUTHEN_STAFF = "Select branch_name from staff_login where user_name = " + "'" + userName + "'" + "and password = " + "'" + passWord + "'";
            rSet =  state.executeQuery(AUTHEN_STAFF);
            if(rSet.next()){
                JOptionPane.showMessageDialog(this, "Login Succesful");
                this.setVisible(false);
                 if (rSet == null) {
                    JOptionPane.showMessageDialog(this, "result set is null");
                    return;
                }
                
                O_OManagerZone.main(new String[]{});
                O_OServer.getO_OManagerZone().managerLabel.setText((String)rSet.getObject("branch_name"));
                
            }
            else{
                JOptionPane.showMessageDialog(this, "Access Denied..Invalid User..Contact Manager", "Error Alert", JOptionPane.ERROR_MESSAGE);}
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error as a result of " + ex.getMessage(), " Error Exception " , JOptionPane.ERROR_MESSAGE);
        }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(O_OAuthenticate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(O_OAuthenticate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(O_OAuthenticate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(O_OAuthenticate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new O_OAuthenticate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel authenPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passWordTField;
    private javax.swing.JComboBox selectionCombo;
    private javax.swing.JTextField userNameTfield;
    // End of variables declaration//GEN-END:variables
}
